version: "3"

services:
  db:
    image: postgres:13
    # restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      PGUSER: postgres
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

    volumes:
      - db-data:/var/lib/postgresql/data
      - ./${BACKUP_DIR}:/db_dump

  app:
    restart: always
    build: .
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi:app
    ports:
      - 127.0.0.1:${LOCAL_APP_PORT}:80
    command: bash run-web.sh
    depends_on:
      - db
      - mqtt

  listener:
    build: .
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi:app
    command: bash run-listener.sh
    depends_on:
      - mqtt
      - db

  mqtt:
    restart: always
    image: simple2b/motovilovka_mqtt_broker
    ports:
      - 127.0.0.1:${MOSQUITTO_API_PORT}:${MOSQUITTO_API_PORT}
      - 127.0.0.1:${MQTT_LOCAL_PORT}:1883
      - 127.0.0.1:${MQTT_LOCAL_WS_PORT}:9001
    volumes:
      - ./mosquitto/config/acl.txt:/mosquitto/config/acl.txt
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_users:/mosquitto/users
      - mosquitto_data:/mosquitto/data
    environment:
      MOSQUITTO_ADMIN_USER: ${MOSQUITTO_ADMIN_USER}
      MOSQUITTO_ADMIN_PASSWORD: ${MOSQUITTO_ADMIN_PASSWORD}
      API_PORT: ${MOSQUITTO_API_PORT}

  backup:
    build: ./pg-backup
    restart: always
    volumes:
      - ./${BACKUP_DIR}:/backup
    links:
      - db
    environment:
      SCHEDULE: "@daily"
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EXTRA_OPTS: "--schema=public --blobs"
      DAYS_HISTORY: 15

volumes:
  mosquitto_users:
  mosquitto_data:
  db-data:
