version: "3"

services:
  db:
    image: postgres:13
    # restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
      POSTGRES_USER: potgres
      PGUSER: potgres
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - 127.0.0.1:${LOCAL_DB_PORT}:5432

    volumes:
      - db-data:/var/lib/postgresql/data
      - ${BACKUP_DIR}:/db_dump

  app:
    restart: always
    build: .
    environment:
      - FLASK_ENV=production
      - FLASK_APP=wsgi:app
      - FLASK_DEBUG=1
      - FLASK_PORT=${FLASK_PORT}
    ports:
      - 127.0.0.1:${LOCAL_APP_PORT}:${FLASK_PORT}
    entrypoint: "bash entry-point.sh"
    depends_on:
      - db

  # celery_worker:
  #   container_name: "celery_worker"
  #   restart: always
  #   image: olegdavimuka/lesson_project
  #   depends_on:
  #     - db
  #   command: >
  #     celery -A worker worker -B --loglevel=INFO

  # redis:
  #   restart: always
  #   image: redis:alpine
  #   ports:
  #     - 127.0.0.1:${REDIS_PORT}:6379
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   command: >
  #     --requirepass ${REDIS_PASSWORD}
  mqtt:
    restart: always
    image: simple2b/motovilovka_mqtt_broker
    ports:
      - 127.0.0.1:${MQTT_LOCAL_PORT-1883}:1883
      - 127.0.0.1:${MQTT_LOCAL_WS_PORT-9001}:9001
    volumes:
      - mosquitto:/mosquitto/config
      - mosquitto:/mosquitto/data
    environment:
      MOSQUITTO_ADMIN_USER: ${MOSQUITTO_ADMIN_USER}
      MOSQUITO_ADMIN_PASSWORD: ${MOSQUITO_ADMIN_PASSWORD}

  backup:
    build: ./pg-backup
    restart: always
    volumes:
      - ${BACKUP_DIR}:/backup
    links:
      - db
    environment:
      SCHEDULE: "@daily"
      POSTGRES_DATABASE: db
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_EXTRA_OPTS: "--schema=public --blobs"
      DAYS_HISTORY: 15

volumes:
  mosquitto:
  db-data:
