"""empty message

Revision ID: 0888694fdc3b
Revises: a54b43b2f5da
Create Date: 2022-08-01 14:06:16.538692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0888694fdc3b'
down_revision = 'a54b43b2f5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('uuid', sa.String(length=64), nullable=True))
    op.drop_column('accounts', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('uid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'uuid')
    # ### end Alembic commands ###
