"""empty message

Revision ID: 0e2e23025f8d
Revises: 0888694fdc3b
Create Date: 2022-08-01 18:30:55.954803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2e23025f8d'
down_revision = '0888694fdc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('uid', sa.String(length=64), nullable=True))
    op.drop_column('accounts', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('uuid', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'uid')
    # ### end Alembic commands ###
