"""accounts.uid

Revision ID: 3f2acb5ca310
Revises: c4b5adb4ae68
Create Date: 2022-08-02 15:05:43.827457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3f2acb5ca310"
down_revision = "c4b5adb4ae68"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("uid", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "uid")
    # ### end Alembic commands ###
