"""empty message

Revision ID: 60e97093d46b
Revises: c7a92fdc01cb
Create Date: 2022-08-01 19:55:40.208243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e97093d46b'
down_revision = 'c7a92fdc01cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('alias', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'alias')
    # ### end Alembic commands ###
