"""sub_device

Revision ID: 7b191afb89e1
Revises: 3f2acb5ca310
Create Date: 2022-08-02 18:56:11.005922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b191afb89e1"
down_revision = "3f2acb5ca310"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("uid", sa.String(length=64), nullable=True),
        sa.Column("alias", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("devices", sa.Column("is_bridge", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("devices", "is_bridge")
    op.drop_table("sub_devices")
    # ### end Alembic commands ###
