"""device.type

Revision ID: 92df111c72c6
Revises: 22ebfd416348
Create Date: 2022-07-25 11:49:09.138094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92df111c72c6'
down_revision = '22ebfd416348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('type', sa.String(length=128), nullable=False))
    op.drop_constraint('devices_name_key', 'devices', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('devices_name_key', 'devices', ['name'])
    op.drop_column('devices', 'type')
    # ### end Alembic commands ###
