"""empty message

Revision ID: a54b43b2f5da
Revises: e6505b560b81
Create Date: 2022-08-01 12:37:04.865893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a54b43b2f5da'
down_revision = 'e6505b560b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('uid', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'uid')
    # ### end Alembic commands ###
