"""device.alias

Revision ID: c4b5adb4ae68
Revises: e6505b560b81
Create Date: 2022-07-31 14:08:05.835037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b5adb4ae68'
down_revision = 'e6505b560b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('alias', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'alias')
    # ### end Alembic commands ###
